############# English navigation ##############

# main menu
[[main]]
name = "Getting Started"
url = "about/"
weight = 2

[[main]]
name = "Courses"
url = "elements/"
weight = 3

[[main]]
name = "Blog"
url = "elements/"
weight = 4

[[main]]
name = "Newsletter"
url = "https://newsletter.piptrends.com"
weight = 5

[[main]]
name = "pip Trends Home"
url = "https://piptrends.com"
weight = 6

[[main]]
name = "More"
weight = 7

[[main]]
parent = "More"
name = "FAQs"
url = "blog/"

[[main]]
parent = "More"
name = "Cheatsheets"
url = "contact/"

[[main]]
parent = "More"
name = "Authors"
url = "authors/"

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
